import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

import { cn } from "@/lib/utils"

const fonstSans = FontSans({
  subsets:["latin"],
  variable:"--font-sans",
})

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fonstSans.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
